<?php declare(strict_types=1);                                                     
                                                                                   
namespace LORIS\biobank\models\container;                                                    
                                                                                   
use LORIS\biobank\Models;                                                          
                                                                                   
final class Types extends Models
{
    public static string $model = Type::class;
}
