<?php declare(strict_types=1);                                                     
                                                                                   
namespace LORIS\biobank\models\specimen;                                                    
                                                                                   
use LORIS\biobank\Models;                                                          
                                                                                   
final class Protocols extends Models
{
    public static string $model = Protocol::class;
}
