<?php declare(strict_types=1);
/**
 * Specimen Analysis Class
 * This class contains an instance of a database handling that is needed to
 * permanently store and retrieve Specimen Analysis instances.
 *
 * PHP Version 7.2
 *
 * @category   Entity
 * @package    Loris
 * @subpackage Biobank
 * @author     Henri Rabalais <henri.rabalais@mcin.ca>
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link       https://www.github.com/aces/Loris/
 */

namespace LORIS\biobank\models\specimen\process;

use LORIS\biobank\models\specimen\Process;

/**
 * Specimen Analysis Class
 * This class contains an instance of a database handling that is needed to
 * permanently store and retrieve Specimen Analysis instances.
 *
 * PHP Version 7.2
 *
 * @category   Entity
 * @package    Loris
 * @subpackage Biobank
 * @author     Henri Rabalais <henri.rabalais@mcin.ca>
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link       https://www.github.com/aces/Loris/
 */

final class Analysis extends Process
{
}

