<?php declare(strict_types=1);
/**
 * Preparation Object Class
 * This class contains an instance of a database handling that is needed to
 * permanently store and retrieve Preparation Object instances.
 *
 * PHP Version 7.2
 *
 * @category Entity
 * @package  Biobank
 * @author   Henri Rabalais <henri.rabalais@mcin.ca>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://www.github.com/aces/Loris/
 */

namespace LORIS\biobank\models\specimen;

use LORIS\biobank\models\specimen\Process;

/**
 * Preparation Object Class
 * This class contains an instance of a database handling that is needed to
 * permanently store and retrieve Preparation Object instances.
 *
 * PHP Version 7.2
 *
 * @category   Entity
 * @package    Loris
 * @subpackage Biobank
 * @author     Henri Rabalais <henri.rabalais@mcin.ca>
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link       https://www.github.com/aces/Loris/
 */
final class Preparation extends Process
{
}

