<?php declare(strict_types=1);                                                     
                                                                                   
namespace LORIS\biobank\models;                                                    
                                                                                   
use LORIS\biobank\Models;   

final class Projects extends Models
{
    public static string $model = Project::class;
}
