<?php declare(strict_types=1);                                                     
                                                                                   
namespace LORIS\biobank\models;                                                    
                                                                                   
use LORIS\biobank\Models;                                                          
                                                                                   
final class Units extends Models
{
    public static string $model = Unit::class;
}
